Roflan/Areas/Administration/Controllers/GeneralController.cs
using Roflan.Areas.Administration.Models;
using Roflan.Entities;
using Roflan.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Roflan.Areas.Administration.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GeneralController : Controller
    {
        private static EFContext context;

        [HttpGet]
        public ActionResult List(int page = 1)
        {
            RegisterListViewModel registerList = new RegisterListViewModel();
            registerList.RegisterList = new List<RegisterViewModel>();
            registerList.PageInfo = new PageInfo();
            int pageSize = 20; // количество объектов на страницу
            foreach (var user in context
                .UserRoles
                .OrderBy(u => u.UserId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize).ToList())
            {
                RegisterViewModel model =
                    new RegisterViewModel();
                model.UserId = user.UserId;
                model.Email = user.Users.Email;
                model.FirstName = user.Users.FirstName;
                model.LastName = user.Users.LastName;
                model.Password = user.Users.Password;
                model.RoleName = user.Roles.Name;
                registerList.RegisterList.Add(model);
            }
            //int countRow = _context.UserRoles.Count();
            //ViewBag.CountUsers = countRow;

            IEnumerable<RegisterViewModel> items = registerList.RegisterList;
            PageInfo pageInfo = new PageInfo
            {
                PageNumber = page,
                PageSize = pageSize,
                TotalItems = context.UserRoles.Count()
            };
            registerList.PageInfo = pageInfo;

            return View(registerList);
        }
        //[HttpGet]
        //public ActionResult Delete(int id)
        //{
        //    var delelCategory = _context
        //        .User
        //        .Select(c => new User
        //        {
        //            Id = c.Id
        //        })
        //        .SingleOrDefault(c => c.Id == id);
        //    return View(delelCategory);
        //}
        [HttpPost]
        public ActionResult Delete(int[] userId)
        {
            for (int i = 0; i < userId.Length; i++)
            {
                int curr = userId[i];
                User user = context.User.SingleOrDefault(c => c.Id == curr);

                if (user.Email != User.Identity.Name)
                {
                    context.User.Remove(user);
                    context.SaveChanges();
                }
            }

            return View();

        }
        public GeneralController()
        {
            context = new EFContext();
        }


        [HttpGet]
        public ActionResult Edit(int id)
        {
            UserRoles user = context.UserRoles.FirstOrDefault(u => u.Users.Id == id);

            RegisterViewModel model = new RegisterViewModel()
            {
                Email = user.Users.Email,
                FirstName = user.Users.FirstName,
                LastName = user.Users.LastName,
                Password = user.Users.Password,
                RoleName = user.Roles.Name
            };

            return View(model);
        }
        [HttpPost]
        public ActionResult Edit()
        {
            return View();
        }

    }
}

Roflan/Controllers/AuthorizeController.cs
using Roflan.Entities;
using Roflan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.Services.Description;

namespace Roflan.Controllers
{
    public class AuthorizeController : Controller
    {
        // GET: Autorize
        private static EFContext context;

        
        public AuthorizeController()
        {
            context = new EFContext();
        }
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(RegisterViewModel model)
        {
            if (context.UserRoles.SingleOrDefault(u => u.Users.Email == model.Email) != null)
            {
                ModelState.AddModelError("Email", "Такий користувач уже зареєстрований");
            }
            else if (ModelState.IsValid)
            {
                //якщо юзер null -> створить його
                if (context.User.SingleOrDefault(t => t.FirstName == model.FirstName
                && t.LastName == model.LastName
                && t.Email == model.Email) == null)
                {
                    var user = new User()
                    {
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        Email = model.Email,
                        Password = model.Password

                    };
                    //RSACryptoServiceProvider RSA = new RSACryptoServiceProvider();
                    var userRole = new UserRoles()
                    {
                        Users = user,
                        Roles = context.Role.Where(x => x.Name == "User").SingleOrDefault()
                    };


                    context.UserRoles.Add(userRole);
                }
                context.SaveChanges();


                return RedirectToAction("Index", "Home");
                //return RedirectToAction("profile", "person", new { personID = Person.personID });
            }
            return View(model);
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid && Membership.ValidateUser(model.Email, model.Password))
            {
                FormsAuthentication.SetAuthCookie(model.Email, false);
                //Roles.AddUserToRole(model.Email, "Admin");
                return RedirectToAction("Index", "Home");
            }
            //errorState
            ModelState.AddModelError("Password", "Wrong Data.");
            return View(model);
        }
        [HttpGet]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            //AuthenticationManager.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Roflan/Controllers/SettingsController.cs
using Roflan.Entities;
using Roflan.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Roflan.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        private static EFContext context;
        private User user;

        public SettingsController()
        {
            context = new EFContext();
        }
        // GET: Settings
        [HttpGet]
        public ActionResult Profile()
        {
            RegisterViewModel model = new RegisterViewModel();
            user = context.User.SingleOrDefault(u => u.Email == User.Identity.Name);
            model.Email = user.Email;
            model.FirstName = user.FirstName;
            model.LastName = user.LastName;
            model.Password = user.Password;

            return View(model);
        }
        [HttpPost]
        
        public ActionResult Edit(EditModel model)
        {
            if (ModelState.IsValid)
            {
                user = context.User.SingleOrDefault(u => u.Email == User.Identity.Name);
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                //user.Password = model.Password;
                context.SaveChanges();

                return RedirectToAction("Profile");
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Roflan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title / @Request.Url.Host.</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home",null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-right">  
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if (!Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Login", "Login", "Authorize")</li>
                            <li>@Html.ActionLink("Register", "Register", "Authorize")</li>
                        }
                        else
                        {
                            <li>
                                <a href=" @Url.Action("Profile", "Settings", null)">
                                    Hello <span class="user-name-text"> @User.Identity.Name</span>
                                </a>
                            </li>
                            <li>
                                <a data-toggle="dropdown">
                                    Settings
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="active"><a href="@Url.Action("Profile","Settings")"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <li><a href="@Url.Action("List", "General", new { area = "Administration" })"><span class="glyphicon glyphicon-inbox"></span> Admin Panel</a></li>
                                    }
                                    <li role="separator" class="divider"></li>
                                    <li>
                                        <a href="@Url.Action("LogOff","Authorize")">
                                            <span class="glyphicon glyphicon-remove-circle"></span> Log Off
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">

        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Україна ще не вмерла</p>
        </footer>
    </div>

    <link href="~/Content/MessagePopUp.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)
</body>
</html>